#!/bin/bash

# ssh stuff
alias sshseas='ssh dcai@seas.harvard.edu'
alias ssheecs='ssh dcai@eecs.harvard.edu'
alias sshnice='ssh dcai@nice.fas.harvard.edu'
alias sshhcs="ssh dicai@hcs.harvard.edu"
alias sshfas="ssh dcai@fas.harvard.edu"
alias sshhraaa="ssh hraaa@hcs.harvard.edu"
alias sshccubed="ssh ccubed@hcs.harvard.edu"
alias sshcs61="ssh dcai@cs61.seas.harvard.edu"
alias ssh61="ssh dcai@cs61-login.seas.harvard.edu"
alias sshcs265="ssh mattisgone@140.247.61.71"
alias sshadama="ssh adama.fas.harvard.edu"
alias ssh161="ssh dcai@cs161.eecs.harvard.edu"

# mysql
alias mysql="/usr/local/mysql/bin/mysql"
alias mysqladmin="/usr/local/mysql/bin/mysqladmin"
alias mysqlstart="sudo /usr/local/mysql/bin/mysqld_safe &"

# other stuff
alias v="vim"
alias g="git"
alias m="hg"
alias s="svn"

# arch linux
alias chromium='chromium --disk-cache-dir=/home/dicai/.config/chromium/cache'
export EDITOR='vim'
alias pacman='sudo pacman_program=pacman-color pacmatic'
#alias ipython='ipython2'

