#!/bin/bash

# use bash vi editing mode
set -o vi

source ~/.bash_aliases

export CLICOLOR=1
#export LSCOLORS=GxDxCxFxBxegedabagacad

# colors
PS1='\[\e[1;34m\]\w \[\e[1;32m\]$ \[\e[m\]'

#alias ls='ls -Fa'

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export PATH=$HOME/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export PATH=/usr/local/share/python:$PATH

export PYTHONPATH=/Users/dicai/Dropbox/Courses/cs222/cs222final/graph_package_branch
export PYTHONPATH=$PYTHONPATH:/Users/dicai/git/graph_package
export PYTHONPATH=/Users/dicai/git/bocpd-seas/src/:$PYTHONPATH
export PYTHONPATH=$PYTHONPATH:/Users/dicai/svn/cocktails
export PYTHONPATH=$PYTHONPATH://usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/
export PYTHONPATH=/Users/dicai/git/:$PYTHONPATH
export PYTHONPATH=/Users/dicai/git/bayes-timeseries:$PYTHONPATH

export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
#PATH="/Library/Frameworks/Python.framework/Versions/2.6/bin:${PATH}"

export VIM_APP_DIR=/usr/local/Cellar/macvim/7.3-66
#export EDITOR=/usr/local/Cellar/macvim/7.3-65/bin/mvim


# added by Anaconda 1.9.2 installer
#export PATH="/Users/dicai/anaconda/bin:$PATH"
