#!/bin/bash

# use bash vi editing mode
set -o vi

source ~/.bash_aliases
 
# automatically open tmux
if which tmux 2>&1 >/dev/null; then
    # if no session is started, start a new session
    test -z ${TMUX} && tmux

    # when quitting tmux, try to attach
    while test -z ${TMUX}; do
        tmux attach || break
    done
fi

export CLICOLOR=1
export LSCOLORS=GxDxCxFxBxegedabagacad

# colors
PS1='\[\e[1;34m\]\w \[\e[1;32m\]$ \[\e[m\]'

alias ls='ls -Fa'

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export PATH=$HOME/bin:$PATH
export PATH=/usr/local/bin:$PATH

export PATH=/opt/local/bin:/opt/local/sbin:$PATH

PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
#PATH="/Library/Frameworks/Python.framework/Versions/2.6/bin:${PATH}"
export PATH
